services:
  virtual-front-end:
    container_name: "vfs-test"
    image: "virtual-front-end"
    working_dir: /tcp-server/virtualFile
    ports:
      - "8080:8080" 
    # build:
    #   context: .
    #   dockerfile: ./dockerfile
    #   platforms:
    #     - linux/arm64
    command: sh -c "cd /tcp-server && make run VM-CONTEXT=1"
