services:
  virtual-front-end:
    container_name: "vfs-test"
    image: "virtual-front-end"
    working_dir: /tcp-server/virtualFile
    ports:
      - "8080:8080" 
    build:
      context: .
      dockerfile: ./dockerfile
      platforms:
        - linux/arm64
    #   args:
    #     VFS_DIR: "../test"
    # command: ["cd", "./tcp-server/virtualFile/","&&","VFS_DIR=../../tmp cargo run"]
    command: sh -c "VFS_DIR=../test cargo run"
    # volumes:
    #   - ${PROJECT_ROOT:-.}/${ENTRY}:/${ENTRY}
    #   - ${PROJECT_ROOT:-.}/.env:/.env
    #   - ${PROJECT_ROOT:-.}/composer.stampy.json:/composer.json
    #   - ${PROJECT_ROOT:-.}:/tmp
