services:
  virtual-front-end:
    container_name: "vfs-test"
    image: "virtual-front-end"
    working_dir: /tcp-server/virtualFile
    ports:
      - "8080:8080" 
    command: sh -c "cd /tcp-server && no-compile-run VM-CONTEXT=1"
