services:
  virtual-front-end:
    container_name: ${CONTAINER_NAME}
    ports:
      - "8080:8080" 
    build:
      context: .
      dockerfile: ./dockerfile
      platforms:
        - linux/arm64
      args:
        TAG: ${TAG}
    command: ["cd tcp-server/virtualFile && ./"]
    # volumes:
    #   - ${PROJECT_ROOT:-.}/${ENTRY}:/${ENTRY}
    #   - ${PROJECT_ROOT:-.}/.env:/.env
    #   - ${PROJECT_ROOT:-.}/composer.stampy.json:/composer.json
    #   - ${PROJECT_ROOT:-.}:/tmp
